
AuctionDataDB = {
	["profiles"] = {
		["Default"] = {
			["myItemTable"] = {
				["Truesilver Ore"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 1439,
					["myQueryFinished"] = false,
					["myDataCount"] = 47,
					["myMinBid"] = 1422,
					["myBid"] = 1147,
					["mySkipPosting"] = false,
					["myMinBO"] = 1553,
				},
				["Essence of Water"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 58241,
					["myQueryFinished"] = false,
					["myDataCount"] = 69,
					["myMinBid"] = 50600,
					["myBid"] = 53878,
					["mySkipPosting"] = false,
					["myMinBO"] = 59000,
				},
				["Silk Cloth"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 513,
					["myQueryFinished"] = false,
					["myDataCount"] = 969,
					["myMinBid"] = 125,
					["myBid"] = 476,
					["mySkipPosting"] = false,
					["myMinBO"] = 182,
				},
				["Mithril Bar"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 3635,
					["myQueryFinished"] = false,
					["myDataCount"] = 49,
					["myMinBid"] = 2138,
					["myBid"] = 2939,
					["mySkipPosting"] = false,
					["myMinBO"] = 2500,
				},
				["Light Leather"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 24,
					["myQueryFinished"] = false,
					["myDataCount"] = 485,
					["myMinBid"] = 14,
					["myBid"] = 18,
					["mySkipPosting"] = false,
					["myMinBO"] = 17,
				},
				["Wool Cloth"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 833,
					["myQueryFinished"] = false,
					["myDataCount"] = 207,
					["myMinBid"] = 25,
					["myBid"] = 241,
					["mySkipPosting"] = false,
					["myMinBO"] = 100,
				},
				["Elemental Air"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 1468,
					["myQueryFinished"] = false,
					["myDataCount"] = 96,
					["myMinBid"] = 250,
					["myBid"] = 1087,
					["mySkipPosting"] = false,
					["myMinBO"] = 400,
				},
				["Chimera Leather"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 6996,
					["myQueryFinished"] = false,
					["myDataCount"] = 7,
					["myMinBid"] = 1253,
					["myBid"] = 5726,
					["mySkipPosting"] = false,
					["myMinBO"] = 1567,
				},
				["Thick Hide"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 664,
					["myQueryFinished"] = false,
					["myDataCount"] = 35,
					["myMinBid"] = 210,
					["myBid"] = 544,
					["mySkipPosting"] = false,
					["myMinBO"] = 310,
				},
				["Rugged Leather"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 1187,
					["myQueryFinished"] = false,
					["myDataCount"] = 224,
					["myMinBid"] = 684,
					["myBid"] = 970,
					["mySkipPosting"] = false,
					["myMinBO"] = 855,
				},
				["Linen Cloth"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 27,
					["myQueryFinished"] = false,
					["myDataCount"] = 1246,
					["myMinBid"] = 0,
					["myBid"] = 9,
					["mySkipPosting"] = false,
					["myMinBO"] = 19,
				},
				["Thick Leather"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 1113,
					["myQueryFinished"] = false,
					["myDataCount"] = 287,
					["myMinBid"] = 450,
					["myBid"] = 672,
					["mySkipPosting"] = false,
					["myMinBO"] = 575,
				},
				["Tin Bar"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 339,
					["myQueryFinished"] = false,
					["myDataCount"] = 122,
					["myMinBid"] = 50,
					["myBid"] = 266,
					["mySkipPosting"] = false,
					["myMinBO"] = 220,
				},
				["Tin Ore"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 335,
					["myQueryFinished"] = false,
					["myDataCount"] = 80,
					["myMinBid"] = 37,
					["myBid"] = 269,
					["mySkipPosting"] = false,
					["myMinBO"] = 100,
				},
				["Copper Ore"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 742,
					["myQueryFinished"] = false,
					["myDataCount"] = 167,
					["myMinBid"] = 200,
					["myBid"] = 634,
					["mySkipPosting"] = false,
					["myMinBO"] = 399,
				},
				["Frostsaber Leather"] = {
					["myBid"] = 0,
					["myBuyout"] = 0,
					["myQueryFinished"] = false,
					["myDataCount"] = 0,
					["myMinBO"] = -1,
					["myMinBid"] = -1,
					["mySkipPosting"] = false,
					["myQueryStarted"] = false,
				},
				["Bronze Bar"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 544,
					["myQueryFinished"] = false,
					["myDataCount"] = 184,
					["myMinBid"] = 250,
					["myBid"] = 436,
					["mySkipPosting"] = false,
					["myMinBO"] = 384,
				},
				["Heavy Leather"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 286,
					["myQueryFinished"] = false,
					["myDataCount"] = 278,
					["myMinBid"] = 132,
					["myBid"] = 199,
					["mySkipPosting"] = false,
					["myMinBO"] = 166,
				},
				["Living Essence"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 6272,
					["myQueryFinished"] = false,
					["myDataCount"] = 152,
					["myMinBid"] = 750,
					["myBid"] = 5774,
					["mySkipPosting"] = false,
					["myMinBO"] = 1900,
				},
				["Elemental Earth"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 7070,
					["myQueryFinished"] = false,
					["myDataCount"] = 110,
					["myMinBid"] = 2530,
					["myBid"] = 6003,
					["mySkipPosting"] = false,
					["myMinBO"] = 4620,
				},
				["Mithril Ore"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 5659,
					["myQueryFinished"] = false,
					["myDataCount"] = 79,
					["myMinBid"] = 375,
					["myBid"] = 2918,
					["mySkipPosting"] = false,
					["myMinBO"] = 1000,
				},
				["Heavy Hide"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 607,
					["myQueryFinished"] = false,
					["myDataCount"] = 56,
					["myMinBid"] = 210,
					["myBid"] = 442,
					["mySkipPosting"] = false,
					["myMinBO"] = 310,
				},
				["Silver Bar"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 2821,
					["myQueryFinished"] = false,
					["myDataCount"] = 139,
					["myMinBid"] = 150,
					["myBid"] = 1232,
					["mySkipPosting"] = false,
					["myMinBO"] = 665,
				},
				["Larval Acid"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 0,
					["myQueryFinished"] = false,
					["myDataCount"] = 0,
					["myMinBid"] = -1,
					["myBid"] = 0,
					["mySkipPosting"] = false,
					["myMinBO"] = -1,
				},
				["Heart of Fire"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 9977,
					["myQueryFinished"] = false,
					["myDataCount"] = 91,
					["myMinBid"] = 600,
					["myBid"] = 7798,
					["mySkipPosting"] = false,
					["myMinBO"] = 6500,
				},
				["Elemental Fire"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 36392,
					["myQueryFinished"] = false,
					["myDataCount"] = 480,
					["myMinBid"] = 600,
					["myBid"] = 30606,
					["mySkipPosting"] = false,
					["myMinBO"] = 23750,
				},
				["Heavy Scorpid Scale"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 1227,
					["myQueryFinished"] = false,
					["myDataCount"] = 9,
					["myMinBid"] = 790,
					["myBid"] = 982,
					["mySkipPosting"] = false,
					["myMinBO"] = 988,
				},
				["Gold Bar"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 1762,
					["myQueryFinished"] = false,
					["myDataCount"] = 67,
					["myMinBid"] = 700,
					["myBid"] = 1195,
					["mySkipPosting"] = false,
					["myMinBO"] = 900,
				},
				["Light Hide"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 103,
					["myQueryFinished"] = false,
					["myDataCount"] = 93,
					["myMinBid"] = 50,
					["myBid"] = 89,
					["mySkipPosting"] = false,
					["myMinBO"] = 66,
				},
				["Globe of Water"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 4469,
					["myQueryFinished"] = false,
					["myDataCount"] = 68,
					["myMinBid"] = 800,
					["myBid"] = 3688,
					["mySkipPosting"] = false,
					["myMinBO"] = 1600,
				},
				["Silver Ore"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 8466,
					["myQueryFinished"] = false,
					["myDataCount"] = 89,
					["myMinBid"] = 112,
					["myBid"] = 5198,
					["mySkipPosting"] = false,
					["myMinBO"] = 1800,
				},
				["Essence of Fire"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 8679,
					["myQueryFinished"] = false,
					["myDataCount"] = 131,
					["myMinBid"] = 3900,
					["myBid"] = 6449,
					["mySkipPosting"] = false,
					["myMinBO"] = 5250,
				},
				["Iron Ore"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 695,
					["myQueryFinished"] = false,
					["myDataCount"] = 175,
					["myMinBid"] = 165,
					["myBid"] = 490,
					["mySkipPosting"] = false,
					["myMinBO"] = 300,
				},
				["Gold Ore"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 1521,
					["myQueryFinished"] = false,
					["myDataCount"] = 90,
					["myMinBid"] = 601,
					["myBid"] = 1135,
					["mySkipPosting"] = false,
					["myMinBO"] = 752,
				},
				["Essence of Earth"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 47787,
					["myQueryFinished"] = false,
					["myDataCount"] = 71,
					["myMinBid"] = 30000,
					["myBid"] = 41781,
					["mySkipPosting"] = false,
					["myMinBO"] = 33300,
				},
				["Iron Bar"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 1288,
					["myQueryFinished"] = false,
					["myDataCount"] = 150,
					["myMinBid"] = 300,
					["myBid"] = 913,
					["mySkipPosting"] = false,
					["myMinBO"] = 645,
				},
				["Mageweave Cloth"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 606,
					["myQueryFinished"] = false,
					["myDataCount"] = 427,
					["myMinBid"] = 300,
					["myBid"] = 463,
					["mySkipPosting"] = false,
					["myMinBO"] = 500,
				},
				["Scorpid Scale"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 7668,
					["myQueryFinished"] = false,
					["myDataCount"] = 16,
					["myMinBid"] = 4912,
					["myBid"] = 6286,
					["mySkipPosting"] = false,
					["myMinBO"] = 4915,
				},
				["Core of Earth"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 16043,
					["myQueryFinished"] = false,
					["myDataCount"] = 76,
					["myMinBid"] = 5000,
					["myBid"] = 12727,
					["mySkipPosting"] = false,
					["myMinBO"] = 6500,
				},
				["Copper Bar"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 673,
					["myQueryFinished"] = false,
					["myDataCount"] = 178,
					["myMinBid"] = 15,
					["myBid"] = 566,
					["mySkipPosting"] = false,
					["myMinBO"] = 575,
				},
				["Rugged Hide"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 5250,
					["myQueryFinished"] = false,
					["myDataCount"] = 72,
					["myMinBid"] = 750,
					["myBid"] = 4080,
					["mySkipPosting"] = false,
					["myMinBO"] = 1400,
				},
				["Runecloth"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 1496,
					["myQueryFinished"] = false,
					["myDataCount"] = 222,
					["myMinBid"] = 428,
					["myBid"] = 596,
					["mySkipPosting"] = false,
					["myMinBO"] = 550,
				},
				["Truesilver Bar"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 4215,
					["myQueryFinished"] = false,
					["myDataCount"] = 91,
					["myMinBid"] = 975,
					["myBid"] = 2947,
					["mySkipPosting"] = false,
					["myMinBO"] = 1282,
				},
				["Thorium Ore"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 29096,
					["myQueryFinished"] = false,
					["myDataCount"] = 22,
					["myMinBid"] = -1,
					["myBid"] = 24355,
					["mySkipPosting"] = false,
					["myMinBO"] = -1,
				},
				["Thorium Bar"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 1793,
					["myQueryFinished"] = false,
					["myDataCount"] = 159,
					["myMinBid"] = 1100,
					["myBid"] = 1416,
					["mySkipPosting"] = false,
					["myMinBO"] = 1245,
				},
				["Elemental Water"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 2065,
					["myQueryFinished"] = false,
					["myDataCount"] = 75,
					["myMinBid"] = 57599,
					["myBid"] = 1655,
					["mySkipPosting"] = false,
					["myMinBO"] = 71999,
				},
				["Essence of Air"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 28354,
					["myQueryFinished"] = false,
					["myDataCount"] = 122,
					["myMinBid"] = 17020,
					["myBid"] = 26569,
					["mySkipPosting"] = false,
					["myMinBO"] = 20000,
				},
				["Medium Hide"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 373,
					["myQueryFinished"] = false,
					["myDataCount"] = 146,
					["myMinBid"] = 165,
					["myBid"] = 250,
					["mySkipPosting"] = false,
					["myMinBO"] = 207,
				},
				["Medium Leather"] = {
					["myQueryStarted"] = false,
					["myBuyout"] = 78,
					["myQueryFinished"] = false,
					["myDataCount"] = 412,
					["myMinBid"] = 49,
					["myBid"] = 58,
					["mySkipPosting"] = false,
					["myMinBO"] = 63,
				},
			},
			["myPendingSales"] = {
				["Thick Leather"] = {
					[1] = {
						["myExpectedReturn"] = 11574,
						["myPricePerUnit"] = 546,
						["myAHCut"] = 546,
						["myDeposit"] = 1200,
						["myStackSize"] = 20,
						["myBuyout"] = 10920,
					},
					[2] = {
						["myExpectedReturn"] = 10374,
						["myPricePerUnit"] = 546,
						["myAHCut"] = 546,
						["myDeposit"] = 0,
						["myStackSize"] = 20,
						["myBuyout"] = 10920,
					},
					[3] = {
						["myExpectedReturn"] = 1158,
						["myPricePerUnit"] = 546,
						["myAHCut"] = 54,
						["myDeposit"] = 120,
						["myStackSize"] = 2,
						["myBuyout"] = 1092,
					},
				},
				["Rugged Hide"] = {
					[1] = {
						["myExpectedReturn"] = 4091,
						["myPricePerUnit"] = 1330,
						["myAHCut"] = 199,
						["myDeposit"] = 300,
						["myStackSize"] = 3,
						["myBuyout"] = 3990,
					},
				},
				["Chimera Leather"] = {
					[1] = {
						["myExpectedReturn"] = 1514,
						["myPricePerUnit"] = 1488,
						["myAHCut"] = 74,
						["myDeposit"] = 100,
						["myStackSize"] = 1,
						["myBuyout"] = 1488,
					},
					[2] = {
						["myExpectedReturn"] = 1414,
						["myPricePerUnit"] = 1488,
						["myAHCut"] = 74,
						["myDeposit"] = 0,
						["myStackSize"] = 1,
						["myBuyout"] = 1488,
					},
				},
				["Thick Hide"] = {
					[1] = {
						["myExpectedReturn"] = 1527,
						["myPricePerUnit"] = 698,
						["myAHCut"] = 69,
						["myDeposit"] = 200,
						["myStackSize"] = 2,
						["myBuyout"] = 1396,
					},
					[2] = {
						["myExpectedReturn"] = 2276,
						["myPricePerUnit"] = 294,
						["myAHCut"] = 88,
						["myDeposit"] = 600,
						["myStackSize"] = 6,
						["myBuyout"] = 1764,
					},
				},
				["Runecloth"] = {
					[1] = {
						["myExpectedReturn"] = 9791,
						["myPricePerUnit"] = 522,
						["myAHCut"] = 443,
						["myDeposit"] = 1360,
						["myStackSize"] = 17,
						["myBuyout"] = 8874,
					},
				},
				["Rugged Leather"] = {
					[1] = {
						["myExpectedReturn"] = 16881,
						["myPricePerUnit"] = 940,
						["myAHCut"] = 799,
						["myDeposit"] = 1700,
						["myStackSize"] = 17,
						["myBuyout"] = 15980,
					},
					[2] = {
						["myExpectedReturn"] = 17428,
						["myPricePerUnit"] = 812,
						["myAHCut"] = 812,
						["myDeposit"] = 2000,
						["myStackSize"] = 20,
						["myBuyout"] = 16240,
					},
					[3] = {
						["myExpectedReturn"] = 16557,
						["myPricePerUnit"] = 812,
						["myAHCut"] = 771,
						["myDeposit"] = 1900,
						["myStackSize"] = 19,
						["myBuyout"] = 15428,
					},
				},
				["Warbear Leather"] = {
				},
				["Mageweave Cloth"] = {
					[1] = {
						["myExpectedReturn"] = 2505,
						["myPricePerUnit"] = 475,
						["myAHCut"] = 118,
						["myDeposit"] = 248,
						["myStackSize"] = 5,
						["myBuyout"] = 2375,
					},
				},
			},
			["mySalesRecord"] = {
				["Thick Hide"] = {
					["mySucessfulSales"] = 1,
					["myFailedSales"] = 2,
					["myAvgPrice"] = 663,
				},
				["Thick Leather"] = {
					["mySucessfulSales"] = 6,
					["myFailedSales"] = 0,
					["myAvgPrice"] = 589,
				},
				["Rugged Leather"] = {
					["mySucessfulSales"] = 2,
					["myFailedSales"] = 0,
					["myAvgPrice"] = 893,
				},
				["Warbear Leather"] = {
					["mySucessfulSales"] = 1,
					["myFailedSales"] = 0,
					["myAvgPrice"] = 855,
				},
				["Rugged Hide"] = {
					["mySucessfulSales"] = 2,
					["myFailedSales"] = 0,
					["myAvgPrice"] = 630,
				},
			},
		},
	},
}
